# Generated by Django 5.1.15 on 2026-07-14 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="target_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="trigger_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="target_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="project",
            name="trigger_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name="ProjectPhase",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("DEV", "Development"),
                            ("SIT", "SIT"),
                            ("UAT", "UAT"),
                            ("PROD", "Production"),
                            ("HYPERCARE", "Hypercare"),
                        ],
                        max_length=20,
                    ),
                ),
                ("planned_start", models.DateTimeField(blank=True, null=True)),
                ("planned_end", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_phase",
                "ordering": ["project", "id"],
                "constraints": [
                    models.UniqueConstraint(fields=("project", "phase"), name="project_phase_uq")
                ],
            },
        ),
    ]
