# Generated by Django 5.1.15 on 2026-07-14 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_client_name_to_trigger"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="project",
            name="project_client__3ae9f5_idx",
        ),
        migrations.RemoveField(
            model_name="historicalproject",
            name="client",
        ),
        migrations.RemoveField(
            model_name="project",
            name="client",
        ),
    ]
