# Generated by Django 5.1.15 on 2026-07-14 04:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0001_initial"),
        ("projects", "0005_remove_project_project_client__3ae9f5_idx_and_more"),
        ("resources", "0001_initial"),
        ("tracking", "0002_remove_historicalrisk_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltask",
            name="api",
        ),
        migrations.RemoveField(
            model_name="projectapiref",
            name="api",
        ),
        migrations.RemoveField(
            model_name="historicalmilestone",
            name="api",
        ),
        migrations.RemoveField(
            model_name="task",
            name="api",
        ),
        migrations.RemoveField(
            model_name="endpoint",
            name="api",
        ),
        migrations.RemoveField(
            model_name="milestone",
            name="api",
        ),
        migrations.RemoveField(
            model_name="endpoint",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="endpoint",
            name="http_method",
        ),
        migrations.RemoveField(
            model_name="endpoint",
            name="owner_employee",
        ),
        migrations.RemoveField(
            model_name="endpoint",
            name="reused_in",
        ),
        migrations.RemoveField(
            model_name="endpoint",
            name="status",
        ),
        migrations.RemoveField(
            model_name="endpoint",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="projectendpointref",
            name="endpoint",
        ),
        migrations.RemoveField(
            model_name="task",
            name="endpoint",
        ),
        migrations.RemoveField(
            model_name="historicaltask",
            name="endpoint",
        ),
        migrations.RemoveField(
            model_name="projectapiref",
            name="project",
        ),
        migrations.RemoveField(
            model_name="projectendpointref",
            name="project",
        ),
        migrations.CreateModel(
            name="SubTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "legacy_code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("description", models.TextField()),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subtasks",
                        to="resources.employee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "priority",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalogs.severitylevel",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalogs.actionstatus",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="projects.task",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subtask",
                "ordering": ["due_date", "-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="ApiComponent",
        ),
        migrations.DeleteModel(
            name="Endpoint",
        ),
        migrations.DeleteModel(
            name="ProjectApiRef",
        ),
        migrations.DeleteModel(
            name="ProjectEndpointRef",
        ),
        migrations.AddIndex(
            model_name="subtask",
            index=models.Index(fields=["task"], name="subtask_task_id_a77622_idx"),
        ),
        migrations.AddIndex(
            model_name="subtask",
            index=models.Index(fields=["status"], name="subtask_status__d19315_idx"),
        ),
        migrations.AddIndex(
            model_name="subtask",
            index=models.Index(fields=["assignee"], name="subtask_assigne_640e5c_idx"),
        ),
    ]
