# Generated by Django 5.1.15 on 2026-09-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphase',
            name='phase',
            field=models.CharField(choices=[('DEV', 'Development'), ('SIT', 'SIT'), ('UAT', 'UAT'), ('HYPERCARE', 'Hypercare'), ('PROD', 'Production')], max_length=20),
        ),
    ]
