# Generated by Django 5.1.15 on 2026-09-06 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projectphase_phase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='consumed_hours',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='planned_hours',
        ),
        migrations.RemoveField(
            model_name='project',
            name='consumed_hours',
        ),
        migrations.RemoveField(
            model_name='project',
            name='planned_hours',
        ),
    ]
