# Generated by Django 5.1.15 on 2026-09-19 03:51

from django.db import migrations, models


def backfill_completed_at(apps, schema_editor):
    """Best-effort: for tasks already DONE, use the earliest delivery_date
    stamped on any of their assignments (see TaskViewSet._stamp_delivery).
    Tasks with no assignments (so no delivery_date) are left NULL — the
    burndown chart treats NULL as 'unknown completion time', not an error."""
    Task = apps.get_model("projects", "Task")
    TaskAssignment = apps.get_model("resources", "TaskAssignment")

    done_task_ids = list(
        Task.objects.filter(status_id="DONE", completed_at__isnull=True).values_list("id", flat=True)
    )
    per_task = {}
    for row in TaskAssignment.objects.filter(
        task_id__in=list(done_task_ids), delivery_date__isnull=False
    ).values("task_id", "delivery_date"):
        current = per_task.get(row["task_id"])
        if current is None or row["delivery_date"] < current:
            per_task[row["task_id"]] = row["delivery_date"]

    for task_id, delivery_date in per_task.items():
        Task.objects.filter(id=task_id).update(completed_at=delivery_date)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0005_teamworkloadperiod"),
        ("projects", "0010_sprint_and_task_sprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Stamped the first time status transitions to DONE (see TaskViewSet._stamp_delivery). "
                           "Backfilled best-effort from TaskAssignment.delivery_date for pre-existing DONE tasks; "
                           "NULL means 'unknown', not 'not done' — used by the sprint burndown chart.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Stamped the first time status transitions to DONE (see TaskViewSet._stamp_delivery). "
                           "Backfilled best-effort from TaskAssignment.delivery_date for pre-existing DONE tasks; "
                           "NULL means 'unknown', not 'not done' — used by the sprint burndown chart.",
                null=True,
            ),
        ),
        migrations.RunPython(backfill_completed_at, noop_reverse),
    ]
