# Generated by Django 5.1.15 on 2026-08-22 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('workitems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='work_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='workitems.workitem'),
        ),
    ]
