"""Leave registry: CRUD/ownership, capacity calendar, workload integration."""
from datetime import datetime, timedelta, timezone as tz
from types import SimpleNamespace

import pytest
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.utils import timezone
from rest_framework.test import APIClient

from apps.core.permissions import ROLE_TEAM
from apps.resources.services import _local_today, employee_workload, leave_calendar
from tests.factories import EmployeeFactory, LeaveFactory, leave_type

pytestmark = pytest.mark.django_db

User = get_user_model()
TODAY = timezone.localdate()
# Weekday anchor so calendar assertions don't depend on the day the suite runs.
NEXT_MONDAY = TODAY + timedelta(days=8 - TODAY.isoweekday())


def _team_client(employee=None):
    user = User.objects.create_user(username=f"tm_{employee.pk if employee else 'none'}",
                                    password="x", employee=employee)
    group, _ = Group.objects.get_or_create(name=ROLE_TEAM)
    user.groups.add(group)
    client = APIClient()
    client.force_authenticate(user)
    return client


def _payload(employee, **extra):
    data = {
        "employee": str(employee.id),
        "leave_type": leave_type().code,
        "start_date": str(TODAY),
        "end_date": str(TODAY + timedelta(days=1)),
    }
    data.update(extra)
    return data


# ----------------------------- API: CRUD + ownership -----------------------------
def test_pm_creates_leave_with_autogenerated_code(pm_client):
    emp = EmployeeFactory()
    res = pm_client.post("/api/leaves/", _payload(emp), format="json")
    assert res.status_code == 201, res.content
    assert res.data["legacy_code"] == "LVE-001"
    assert res.data["employee_name"] == emp.name


def test_rejects_reversed_dates(pm_client):
    emp = EmployeeFactory()
    res = pm_client.post(
        "/api/leaves/",
        _payload(emp, start_date=str(TODAY), end_date=str(TODAY - timedelta(days=1))),
        format="json")
    assert res.status_code == 400


def test_team_member_creates_own_leave_only():
    mine, other = EmployeeFactory(), EmployeeFactory()
    client = _team_client(mine)
    assert client.post("/api/leaves/", _payload(mine), format="json").status_code == 201
    assert client.post("/api/leaves/", _payload(other), format="json").status_code == 403


def test_team_member_cannot_touch_others_leave():
    mine, other = EmployeeFactory(), EmployeeFactory()
    leave = LeaveFactory(employee=other)
    client = _team_client(mine)
    res = client.patch(f"/api/leaves/{leave.id}/", {"notes": "hey"}, format="json")
    assert res.status_code == 403
    assert client.delete(f"/api/leaves/{leave.id}/").status_code == 403


def test_team_member_deletes_own_leave():
    mine = EmployeeFactory()
    leave = LeaveFactory(employee=mine)
    client = _team_client(mine)
    assert client.delete(f"/api/leaves/{leave.id}/").status_code == 204
    leave.refresh_from_db()
    assert leave.is_active is False  # soft-delete


def test_unlinked_team_member_cannot_create():
    client = _team_client(None)
    res = client.post("/api/leaves/", _payload(EmployeeFactory()), format="json")
    assert res.status_code == 403


# ----------------------------- calendar -----------------------------
def test_calendar_counts_and_threshold():
    e1, e2, e3, e4 = EmployeeFactory.create_batch(4)
    LeaveFactory(employee=e1, start_date=NEXT_MONDAY, end_date=NEXT_MONDAY + timedelta(days=2))
    LeaveFactory(employee=e2, start_date=NEXT_MONDAY, end_date=NEXT_MONDAY)

    days = leave_calendar(NEXT_MONDAY, NEXT_MONDAY + timedelta(days=3), threshold=0.25)
    assert [d["absent_count"] for d in days] == [2, 1, 1, 0]
    assert days[0]["headcount"] == 4
    assert days[0]["absent_pct"] == 0.5
    assert days[0]["alert"] == "OVER_THRESHOLD"   # 2/4 > 0.25
    assert days[1]["alert"] == "OK"               # 1/4 == 0.25, not over
    assert days[3]["absent"] == []


def test_calendar_skips_non_working_days():
    emp = EmployeeFactory()  # no schedule -> Mon..Fri
    friday = NEXT_MONDAY + timedelta(days=4)
    LeaveFactory(employee=emp, start_date=friday, end_date=friday + timedelta(days=3))

    days = leave_calendar(friday, friday + timedelta(days=3), threshold=0)
    fri, sat, sun, mon = days
    assert fri["absent_count"] == 1 and fri["headcount"] == 1
    assert sat["absent_count"] == 0 and sat["headcount"] == 0
    assert sat["alert"] == "OK"  # weekends never alert
    assert sun["absent_count"] == 0
    assert mon["absent_count"] == 1  # back to a working day


def test_calendar_counts_people_not_rows():
    emp = EmployeeFactory()
    LeaveFactory(employee=emp, start_date=NEXT_MONDAY, end_date=NEXT_MONDAY)
    LeaveFactory(employee=emp, start_date=NEXT_MONDAY, end_date=NEXT_MONDAY)  # overlapping rows
    days = leave_calendar(NEXT_MONDAY, NEXT_MONDAY, threshold=0.9)
    assert days[0]["absent_count"] == 1


def test_calendar_ignores_soft_deleted():
    emp = EmployeeFactory()
    leave = LeaveFactory(employee=emp, start_date=NEXT_MONDAY, end_date=NEXT_MONDAY)
    leave.soft_delete()
    days = leave_calendar(NEXT_MONDAY, NEXT_MONDAY)
    assert days[0]["absent_count"] == 0


def test_calendar_endpoint_requires_auth_and_returns_days(pm_client):
    assert APIClient().get("/api/resources/leave-calendar/").status_code == 401
    emp = EmployeeFactory()
    LeaveFactory(employee=emp, start_date=NEXT_MONDAY, end_date=NEXT_MONDAY)
    res = pm_client.get(
        f"/api/resources/leave-calendar/?start={NEXT_MONDAY}&end={NEXT_MONDAY}&threshold=0")
    assert res.status_code == 200
    assert res.data[0]["absent_count"] == 1
    assert res.data[0]["alert"] == "OVER_THRESHOLD"


def test_calendar_rejects_bad_range(pm_client):
    res = pm_client.get(
        f"/api/resources/leave-calendar/?start={TODAY}&end={TODAY - timedelta(days=1)}")
    assert res.status_code == 400


# ----------------------------- workload integration -----------------------------
def _row(emp):
    return next(r for r in employee_workload() if r["employee_id"] == str(emp.id))


def test_leave_reduces_capacity_and_flags_today():
    emp = EmployeeFactory()  # weekly 40h, no schedule -> Mon..Fri workdays
    monday = TODAY - timedelta(days=TODAY.isoweekday() - 1)
    LeaveFactory(employee=emp, start_date=monday, end_date=monday + timedelta(days=6))
    row = _row(emp)
    assert row["leave_days"] == 5          # only working days count
    assert row["capacity_hours"] == 0.0    # whole week off
    assert row["on_leave_today"] is True
    assert row["on_shift_now"] is False


def test_single_leave_day_drops_one_fifth():
    emp = EmployeeFactory()
    monday = TODAY - timedelta(days=TODAY.isoweekday() - 1)
    LeaveFactory(employee=emp, start_date=monday, end_date=monday)
    row = _row(emp)
    assert row["leave_days"] == 1
    assert row["capacity_hours"] == 32.0   # 40 - 40/5


def test_weekend_leave_costs_nothing():
    emp = EmployeeFactory()
    saturday = TODAY - timedelta(days=TODAY.isoweekday() - 1) + timedelta(days=5)
    LeaveFactory(employee=emp, start_date=saturday, end_date=saturday + timedelta(days=1))
    row = _row(emp)
    assert row["leave_days"] == 0
    assert row["capacity_hours"] == 40.0


def test_no_leave_keeps_capacity():
    emp = EmployeeFactory()
    row = _row(emp)
    assert row["leave_days"] == 0
    assert row["capacity_hours"] == 40.0
    assert row["on_leave_today"] is False


# ----------------------------- unit: _local_today -----------------------------
# 03:00 UTC on Jul 17: Colombia (UTC-5) is still on Jul 16; Manila (UTC+8) is Jul 17.
UTC_NOW = datetime(2026, 7, 17, 3, 0, tzinfo=tz.utc)


def _emp_with_offset(offset):
    timezone_ = SimpleNamespace(utc_offset=offset) if offset is not None else None
    return SimpleNamespace(timezone=timezone_)


def test_local_today_uses_employee_timezone():
    """Repro of the reported bug: a leave registered for 'tomorrow' must not
    flag a UTC-5 dev as on leave the evening before (server runs on UTC)."""
    assert str(_local_today(_emp_with_offset(-5), UTC_NOW)) == "2026-07-16"
    assert str(_local_today(_emp_with_offset(8), UTC_NOW)) == "2026-07-17"
    assert str(_local_today(_emp_with_offset(None), UTC_NOW)) == "2026-07-17"
