"""Country public holidays: CRUD/permissions, calendar and workload effects."""
from datetime import timedelta

import pytest
from django.utils import timezone

from apps.resources.services import employee_workload, leave_calendar
from tests.factories import EmployeeFactory, HolidayFactory, LeaveFactory, location

pytestmark = pytest.mark.django_db

TODAY = timezone.localdate()
# Weekday anchors so assertions don't depend on the day the suite runs.
NEXT_MONDAY = TODAY + timedelta(days=8 - TODAY.isoweekday())
THIS_MONDAY = TODAY - timedelta(days=TODAY.isoweekday() - 1)  # inside workload's window


# ----------------------------- API: CRUD + permissions -----------------------------
def test_pm_creates_holiday_with_autogenerated_code(pm_client):
    location()
    res = pm_client.post("/api/holidays/", {
        "name": "Independence Day", "location": "COLOMBIA", "date": str(NEXT_MONDAY),
    }, format="json")
    assert res.status_code == 201, res.content
    assert res.data["legacy_code"] == "HOL-001"
    assert res.data["location_name"] == "Colombia"


def test_rejects_duplicate_date_and_country(pm_client):
    HolidayFactory(date=NEXT_MONDAY, location=location())
    res = pm_client.post("/api/holidays/", {
        "name": "Duplicate", "location": "COLOMBIA", "date": str(NEXT_MONDAY),
    }, format="json")
    assert res.status_code == 400


def test_viewer_reads_but_cannot_write(viewer_client):
    HolidayFactory(date=NEXT_MONDAY)
    assert viewer_client.get("/api/holidays/").status_code == 200
    res = viewer_client.post("/api/holidays/", {
        "name": "Nope", "location": "COLOMBIA", "date": str(NEXT_MONDAY + timedelta(days=1)),
    }, format="json")
    assert res.status_code == 403


# ----------------------------- calendar -----------------------------
def test_calendar_holiday_drops_country_from_headcount():
    co = location("COLOMBIA", "Colombia")
    ph = location("PHILIPPINES", "Philippines")
    co_emp1 = EmployeeFactory(location=co)
    EmployeeFactory(location=co)
    ph_emp = EmployeeFactory(location=ph)
    HolidayFactory(date=NEXT_MONDAY, location=co, name="Independence Day")
    # the Colombian's leave lands on their holiday: it must not count as absence
    LeaveFactory(employee=co_emp1, start_date=NEXT_MONDAY, end_date=NEXT_MONDAY)
    LeaveFactory(employee=ph_emp, start_date=NEXT_MONDAY, end_date=NEXT_MONDAY)

    [day] = leave_calendar(NEXT_MONDAY, NEXT_MONDAY)
    assert day["headcount"] == 1  # both Colombians are off for the holiday
    assert day["absent_count"] == 1
    assert day["absent"][0]["employee_id"] == str(ph_emp.id)
    assert day["holidays"] == [{
        "location": "COLOMBIA", "location_name": "Colombia", "name": "Independence Day",
    }]
    assert day["alert"] == "OVER_THRESHOLD"  # the only scheduled person is out


def test_calendar_day_without_holidays_has_empty_list():
    EmployeeFactory()
    [day] = leave_calendar(NEXT_MONDAY, NEXT_MONDAY)
    assert day["holidays"] == []
    assert day["headcount"] == 1


# ----------------------------- workload -----------------------------
def test_holiday_reduces_capacity_only_for_its_country():
    co = location("COLOMBIA", "Colombia")
    ph = location("PHILIPPINES", "Philippines")
    co_emp = EmployeeFactory(location=co, weekly_hours=40)
    ph_emp = EmployeeFactory(location=ph, weekly_hours=40)
    HolidayFactory(date=THIS_MONDAY, location=co)

    rows = {r["name"]: r for r in employee_workload()}
    assert rows[co_emp.name]["capacity_hours"] == 32.0
    assert rows[co_emp.name]["holiday_days"] == 1
    assert rows[ph_emp.name]["capacity_hours"] == 40.0
    assert rows[ph_emp.name]["holiday_days"] == 0


def test_leave_on_holiday_is_one_day_off_not_two():
    co = location()
    emp = EmployeeFactory(location=co, weekly_hours=40)
    HolidayFactory(date=THIS_MONDAY, location=co)
    LeaveFactory(employee=emp, start_date=THIS_MONDAY, end_date=THIS_MONDAY)

    [row] = employee_workload()
    assert row["capacity_hours"] == 32.0
    assert row["leave_days"] == 1
    assert row["holiday_days"] == 1


def test_holiday_today_flags_employee_off():
    co = location()
    EmployeeFactory(location=co)  # no timezone: local today == server date
    HolidayFactory(date=TODAY, location=co)

    [row] = employee_workload()
    assert row["holiday_today"] is True
    assert row["on_shift_now"] is False
    assert row["on_leave_today"] is False
