"""Personal notes: CRUD abierto a cualquier autenticado, aislamiento por usuario."""
import pytest
from django.contrib.auth import get_user_model
from rest_framework.test import APIClient

from apps.notes.models import Note

pytestmark = pytest.mark.django_db

User = get_user_model()


def _client(username="alice"):
    """Usuario autenticado SIN rol: las notas no dependen de grupos."""
    user = User.objects.create_user(username=username, password="x")
    client = APIClient()
    client.force_authenticate(user)
    return client, user


# ----------------------------- CRUD -----------------------------
def test_roleless_user_creates_note_with_autogenerated_code():
    client, _ = _client()
    res = client.post("/api/notes/", {"title": "Remember the milk"}, format="json")
    assert res.status_code == 201, res.content
    assert res.data["legacy_code"] == "NTE-001"
    assert res.data["category"] == Note.Category.TODO
    assert res.data["priority"] == Note.Priority.MEDIUM
    assert res.data["status"] == Note.Status.OPEN

    res2 = client.post("/api/notes/", {"title": "Second"}, format="json")
    assert res2.data["legacy_code"] == "NTE-002"


def test_update_own_note():
    client, _ = _client()
    note_id = client.post("/api/notes/", {"title": "Draft"}, format="json").data["id"]
    res = client.patch(f"/api/notes/{note_id}/",
                       {"status": "COMPLETED", "pinned": True}, format="json")
    assert res.status_code == 200
    assert res.data["status"] == "COMPLETED"
    assert res.data["pinned"] is True


def test_delete_is_soft():
    client, _ = _client()
    note_id = client.post("/api/notes/", {"title": "Gone"}, format="json").data["id"]
    res = client.delete(f"/api/notes/{note_id}/")
    assert res.status_code == 204
    note = Note.objects.get(pk=note_id)
    assert note.is_active is False


# ----------------------------- Aislamiento por usuario -----------------------------
def test_users_only_see_their_own_notes():
    client_a, _ = _client("alice")
    client_b, _ = _client("bob")
    client_a.post("/api/notes/", {"title": "Alice's secret"}, format="json")

    res = client_b.get("/api/notes/")
    assert res.status_code == 200
    assert res.data["count"] == 0


def test_foreign_note_is_404_for_all_verbs():
    client_a, _ = _client("alice")
    client_b, _ = _client("bob")
    note_id = client_a.post("/api/notes/", {"title": "Private"}, format="json").data["id"]

    assert client_b.get(f"/api/notes/{note_id}/").status_code == 404
    assert client_b.patch(f"/api/notes/{note_id}/", {"title": "Hack"},
                          format="json").status_code == 404
    assert client_b.delete(f"/api/notes/{note_id}/").status_code == 404


def test_unauthenticated_is_rejected(api_client):
    assert api_client.get("/api/notes/").status_code == 401


# ----------------------------- Filtros -----------------------------
def test_filters_by_status_and_pinned():
    client, _ = _client()
    client.post("/api/notes/", {"title": "Open pinned", "pinned": True}, format="json")
    client.post("/api/notes/", {"title": "Done", "status": "COMPLETED"}, format="json")

    open_res = client.get("/api/notes/?status=OPEN")
    assert open_res.data["count"] == 1
    assert open_res.data["results"][0]["title"] == "Open pinned"

    pinned_res = client.get("/api/notes/?pinned=true")
    assert pinned_res.data["count"] == 1

    all_res = client.get("/api/notes/")
    assert all_res.data["count"] == 2
