# Generated by Django 5.1.15 on 2026-07-23 04:01

from django.db import migrations, models


def bump_40_to_42(apps, schema_editor):
    Employee = apps.get_model("resources", "Employee")
    Employee.objects.filter(weekly_hours=40).update(weekly_hours=42)


def revert_42_to_40(apps, schema_editor):
    Employee = apps.get_model("resources", "Employee")
    Employee.objects.filter(weekly_hours=42).update(weekly_hours=40)


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='weekly_hours',
            field=models.DecimalField(decimal_places=2, default=42, max_digits=6),
        ),
        migrations.RunPython(bump_40_to_42, revert_42_to_40),
    ]
