# Generated by Django 5.1.15 on 2026-09-06 04:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0002_note_work_item'),
        ('projects', '0009_remove_historicalproject_consumed_hours_and_more'),
        ('tickets', '0002_rename_pending_customer_to_paused'),
        ('workitems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('url', models.URLField(max_length=500)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='notes.note')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='projects.project')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='tickets.ticket')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('work_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='workitems.workitem')),
            ],
            options={
                'db_table': 'link',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project'], name='link_project_b0798a_idx'), models.Index(fields=['note'], name='link_note_id_0bb535_idx'), models.Index(fields=['ticket'], name='link_ticket__e12f74_idx'), models.Index(fields=['work_item'], name='link_work_it_74e3e7_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('note__isnull', True), ('project__isnull', False), ('ticket__isnull', True), ('work_item__isnull', True)), models.Q(('note__isnull', False), ('project__isnull', True), ('ticket__isnull', True), ('work_item__isnull', True)), models.Q(('note__isnull', True), ('project__isnull', True), ('ticket__isnull', False), ('work_item__isnull', True)), models.Q(('note__isnull', True), ('project__isnull', True), ('ticket__isnull', True), ('work_item__isnull', False)), _connector='OR'), name='link_exactly_one_owner')],
            },
        ),
    ]
