# Generated by Django 5.1.15 on 2026-07-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActionOrigin",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "action_origin",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ActionStatus",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_closed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "action_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApiStatus",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "api_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmployeeLevel",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "employee_level",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmployeeStatus",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "employee_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EndpointStatus",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_done", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "endpoint_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HealthStatus",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "health_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HttpMethod",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "http_method",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IssueStatus",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_closed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "issue_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "location",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MilestoneStatus",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_closed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "milestone_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectStatus",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_closed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "project_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "project_type",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RiskStatus",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_closed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "risk_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SeverityLevel",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("weight", models.SmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "severity level",
                "db_table": "severity_level",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("start_hour", models.SmallIntegerField(blank=True, null=True)),
                ("end_hour", models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "shift",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskStatus",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_closed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "task_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskType",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "task_type",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Timezone",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("utc_offset", models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                "db_table": "timezone",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UpdateType",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "update_type",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
    ]
