# Generated by Django 5.1.15 on 2026-07-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketStatus",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_closed", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "ticket statuses",
                "db_table": "ticket_status",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
    ]
