# Generated by Django 5.1.15 on 2026-07-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0002_ticketstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                ("code", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "leave_type",
                "ordering": ["sort_order", "name"],
                "abstract": False,
            },
        ),
    ]
